inputs:
  options:
    description: extra options for config_brpc.sh
    required: false
runs:
  using: "composite"
  steps:
    - run: sudo apt-get update && sudo apt-get install -y libgtest-dev cmake gdb libstdc++6-9-dbg && cd /usr/src/gtest && export CC=clang && export CXX=clang++ && sudo cmake . && sudo make -j ${{env.proc_num}} && sudo mv lib/libgtest* /usr/lib/
      shell: bash
    - run: sh config_brpc.sh --headers="/libunwind/include /usr/include" --libs="/libunwind/lib /usr/lib /usr/lib64" ${{inputs.options}}
      shell: bash
