name: Build and Test on Linux

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  proc_num: $(nproc)

jobs:
  clang-unittest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-essential-dependences
      - uses: ./.github/actions/init-ut-make-config
        with:
          options: --cc=clang --cxx=clang++
      - name: compile tests
        run: |
          cat config.mk
          cd test
          make -j ${{env.proc_num}} brpc_server_unittest
      - name: run tests
        run: |
          cd test
          sh ./run_tests.sh
